// AUTO-GENERATED by scripts/build-english-details.mjs — do not edit by hand.
// Sub-headings copied from the English textbook text in the knowledge database.
// Regenerate with: npm run build:english
export const ENGLISH_DETAILS = {
 "G10-ENGL-U1-S2": [
  {
   "number": "1.2.1",
   "title": "Pronouncing Short Vowels, Long Vowels and",
   "page": 3
  },
  {
   "number": "1.2.2",
   "title": "Small Talks: Asking for Opinions",
   "page": 5
  }
 ],
 "G10-ENGL-U1-S3": [
  {
   "number": "1.3.1",
   "title": "Vocabulary : Part I",
   "page": 12
  },
  {
   "number": "1.3.2",
   "title": "Vocabulary : Part II",
   "page": 13
  },
  {
   "number": "1.3.3",
   "title": "Word Formation",
   "page": 13
  },
  {
   "number": "1.3.4",
   "title": "Phrasal Verbs",
   "page": 16
  }
 ],
 "G10-ENGL-U1-S4": [
  {
   "number": "1.4.1",
   "title": "Degrees of Comparison",
   "page": 18
  },
  {
   "number": "1.4.2",
   "title": "Simple Present Tense and Present Perfect Tense",
   "page": 24
  },
  {
   "number": "1.4.3",
   "title": "Using Relative Pronouns",
   "page": 27
  },
  {
   "number": "1.4.4",
   "title": "Using suggest, should, ought to and had better",
   "page": 31
  }
 ],
 "G10-ENGL-U1-S5": [
  {
   "number": "1.5.1",
   "title": "Guided Writing",
   "page": 33
  },
  {
   "number": "1.5.2",
   "title": "Using Punctuations",
   "page": 35
  }
 ],
 "G10-ENGL-U2-S2": [
  {
   "number": "2.2.1",
   "title": "Pronunciation",
   "page": 39
  },
  {
   "number": "2.2.2",
   "title": "Giving Advice and Warnings",
   "page": 40
  }
 ],
 "G10-ENGL-U2-S3": [
  {
   "number": "2.3.1",
   "title": "Vocabulary",
   "page": 48
  },
  {
   "number": "2.3.2",
   "title": "Phrasal Verbs",
   "page": 49
  }
 ],
 "G10-ENGL-U2-S4": [
  {
   "number": "2.4.1",
   "title": "Simple Past Tense",
   "page": 50
  }
 ],
 "G10-ENGL-U2-S5": [
  {
   "number": "2.5.1",
   "title": "Practising Writing Different Types of Sentences",
   "page": 52
  },
  {
   "number": "2.5.2",
   "title": "Summarizing a Text",
   "page": 55
  },
  {
   "number": "2.5.3",
   "title": "Describing People",
   "page": 58
  },
  {
   "number": "2.5.4",
   "title": "Punctuations",
   "page": 60
  }
 ],
 "G10-ENGL-U3-S2": [
  {
   "number": "3.2.1",
   "title": "Pronunciation",
   "page": 69
  },
  {
   "number": "3.2.2",
   "title": "Expressing Personal Thoughts and Beliefs",
   "page": 70
  },
  {
   "number": "3.2.3",
   "title": "Using “so” and “neither”",
   "page": 72
  }
 ],
 "G10-ENGL-U3-S4": [
  {
   "number": "3.4.1",
   "title": "Word Formation: Conversion",
   "page": 78
  },
  {
   "number": "3.4.2",
   "title": "Phrasal Verbs",
   "page": 81
  }
 ],
 "G10-ENGL-U3-S5": [
  {
   "number": "3.5.1",
   "title": "Adverbs of Time and Frequency",
   "page": 82
  },
  {
   "number": "3.5.2",
   "title": "Adverbs of Manner",
   "page": 83
  },
  {
   "number": "3.5.3",
   "title": "Tense: Reviewing The Simple Present Tense",
   "page": 86
  },
  {
   "number": "3.5.4",
   "title": "Prepositions",
   "page": 86
  }
 ],
 "G10-ENGL-U3-S6": [
  {
   "number": "3.6.1",
   "title": "Punctuations",
   "page": 89
  },
  {
   "number": "3.6.2",
   "title": "Writing a Narrative Paragraph",
   "page": 90
  }
 ],
 "G10-ENGL-U4-S2": [
  {
   "number": "4.2.1",
   "title": "Pronouncing the plural marking morphemes –s and",
   "page": 95
  },
  {
   "number": "4.2.2",
   "title": "Revision: Pronouncing interdental voiced and",
   "page": 95
  },
  {
   "number": "4.2.3",
   "title": "Pronouncing the diphthongs [ai] and [ei]",
   "page": 96
  },
  {
   "number": "4.2.4",
   "title": "Revision: Expressing Agreement and Disagreement",
   "page": 96
  },
  {
   "number": "4.2.5",
   "title": "Revision: Giving Opinions",
   "page": 97
  }
 ],
 "G10-ENGL-U4-S3": [
  {
   "number": "4.3.1",
   "title": "Extracting Main Idea from a Paragraph",
   "page": 103
  },
  {
   "number": "4.3.2",
   "title": "Inference questions",
   "page": 103
  }
 ],
 "G10-ENGL-U4-S4": [
  {
   "number": "4.4.1",
   "title": "Word formation",
   "page": 105
  },
  {
   "number": "4.4.2",
   "title": "Practising Phrasal Verbs with “get”",
   "page": 107
  }
 ],
 "G10-ENGL-U4-S5": [
  {
   "number": "4.5.1",
   "title": "Using “be+going to + infinitive” and “will +",
   "page": 107
  },
  {
   "number": "4.5.2",
   "title": "Present Continuous Tense",
   "page": 109
  },
  {
   "number": "4.5.4",
   "title": "Clauses of Result",
   "page": 112
  }
 ],
 "G10-ENGL-U4-S6": [
  {
   "number": "4.6.1",
   "title": "Report Writing",
   "page": 115
  },
  {
   "number": "4.6.2",
   "title": "Punctuations",
   "page": 118
  }
 ],
 "G10-ENGL-U5-S2": [
  {
   "number": "5.2.1",
   "title": "Practising Pronouncing vowels and Diphthongs",
   "page": 122
  },
  {
   "number": "5.2.2",
   "title": "Describing Processes",
   "page": 122
  }
 ],
 "G10-ENGL-U5-S4": [
  {
   "number": "5.4.1",
   "title": "Word Formation: Blending and Clipping",
   "page": 128
  },
  {
   "number": "5.4.2",
   "title": "Phrasal Verbs",
   "page": 130
  }
 ],
 "G10-ENGL-U5-S5": [
  {
   "number": "5.5.1",
   "title": "Simple Present Active and Passive Sentences",
   "page": 131
  },
  {
   "number": "5.5.2",
   "title": "Subject-verb Agreement",
   "page": 135
  },
  {
   "number": "5.5.3",
   "title": "Using “do” and “make”",
   "page": 138
  }
 ],
 "G10-ENGL-U5-S6": [
  {
   "number": "5.6.1",
   "title": "Writing a Topic Sentence for a paragraph",
   "page": 139
  },
  {
   "number": "5.6.2",
   "title": "Dictation",
   "page": 143
  }
 ],
 "G10-ENGL-U6-S2": [
  {
   "number": "6.2.1",
   "title": "Pronunciation",
   "page": 148
  }
 ],
 "G10-ENGL-U6-S4": [
  {
   "number": "6.4.1",
   "title": "Word Formation",
   "page": 156
  }
 ],
 "G10-ENGL-U6-S5": [
  {
   "number": "6.5.1",
   "title": "Reviewing present perfect, simple past, and past",
   "page": 159
  },
  {
   "number": "6.5.2",
   "title": "Using different prepositions",
   "page": 163
  },
  {
   "number": "6.5.3",
   "title": "Adverb clauses of Purpose",
   "page": 165
  }
 ],
 "G10-ENGL-U6-S6": [
  {
   "number": "6.6.1",
   "title": "Revision: Summary Writing",
   "page": 166
  },
  {
   "number": "6.6.2",
   "title": "Interpreting Graphs",
   "page": 172
  },
  {
   "number": "6.6.3",
   "title": "Spelling Rules",
   "page": 173
  }
 ],
 "G10-ENGL-U7-S1": [
  {
   "number": "7.1.1",
   "title": "Ethiopia: The Land of Origins",
   "page": 176
  }
 ],
 "G10-ENGL-U7-S2": [
  {
   "number": "7.2.1",
   "title": "Revision: Pronouncing [æ], [ə] and [j] Vowels",
   "page": 179
  },
  {
   "number": "7.2.2",
   "title": "Revision: Expressing Opinions through Agreement",
   "page": 181
  }
 ],
 "G10-ENGL-U7-S3": [
  {
   "number": "7.3.1",
   "title": "Part I: Ethiopia Through Writers’ Eyes",
   "page": 191
  },
  {
   "number": "7.3.2",
   "title": "Part II: Ethiopia’s Heritages Registered by",
   "page": 194
  }
 ],
 "G10-ENGL-U7-S4": [
  {
   "number": "7.4.1",
   "title": "Word Formation: Prefixes and suffixes",
   "page": 197
  },
  {
   "number": "7.4.2",
   "title": "Revision : Using Phrasal Verbs in Communications",
   "page": 199
  }
 ],
 "G10-ENGL-U7-S5": [
  {
   "number": "7.5.1",
   "title": "Conditional Sentences",
   "page": 202
  },
  {
   "number": "7.5.2",
   "title": "Direct and Reported Speech",
   "page": 207
  }
 ],
 "G10-ENGL-U7-S6": [
  {
   "number": "7.6.1",
   "title": "Argumentative Essay",
   "page": 211
  }
 ],
 "G10-ENGL-U8-S4": [
  {
   "number": "8.4.1",
   "title": "Types of Word Formation Processes",
   "page": 232
  },
  {
   "number": "8.4.2",
   "title": "Revision: Phrasal Verbs",
   "page": 233
  }
 ],
 "G10-ENGL-U8-S5": [
  {
   "number": "8.5.1",
   "title": "Quantifiers",
   "page": 235
  },
  {
   "number": "8.5.2",
   "title": "Clauses of reason",
   "page": 236
  },
  {
   "number": "8.5.3",
   "title": "Revision: Clauses of manner",
   "page": 237
  },
  {
   "number": "8.5.4",
   "title": "Tense",
   "page": 238
  }
 ],
 "G10-ENGL-U8-S6": [
  {
   "number": "8.6.1",
   "title": "Revision: Interpreting Graphs",
   "page": 241
  }
 ],
 "G10-ENGL-U9-S3": [
  {
   "number": "9.3.1",
   "title": "Comprehension Questions",
   "page": 251
  }
 ],
 "G10-ENGL-U9-S4": [
  {
   "number": "9.4.1",
   "title": "Writing Informal letter",
   "page": 253
  },
  {
   "number": "9.4.2",
   "title": "Writing a Formal Letter",
   "page": 255
  }
 ],
 "G10-ENGL-U9-S5": [
  {
   "number": "9.5.1",
   "title": "Revision: Conditional Sentences",
   "page": 256
  },
  {
   "number": "9.5.2",
   "title": "Articles: Definite and Indefinite",
   "page": 258
  },
  {
   "number": "9.5.3",
   "title": "Tenses",
   "page": 261
  },
  {
   "number": "9.5.4",
   "title": "State verbs: Thoughts and opinions",
   "page": 269
  }
 ],
 "G10-ENGL-U9-S6": [
  {
   "number": "9.6.1",
   "title": "Word formation: Borrowing words",
   "page": 271
  },
  {
   "number": "9.6.2",
   "title": "Phrasal verbs",
   "page": 272
  }
 ],
 "G10-ENGL-U10-S4": [
  {
   "number": "10.4.1",
   "title": "Phrasal Verbs",
   "page": 283
  }
 ],
 "G10-ENGL-U10-S5": [
  {
   "number": "10.5.1",
   "title": "Connectors of Compare-Contrast",
   "page": 285
  },
  {
   "number": "10.5.2",
   "title": "Modal auxiliaries: (ought to, should, must, have to",
   "page": 288
  },
  {
   "number": "10.5.3",
   "title": "Direct and indirect Object",
   "page": 293
  },
  {
   "number": "10.5.4",
   "title": "Transitive and intransitive verbs",
   "page": 294
  }
 ],
 "G10-ENGL-U10-S6": [
  {
   "number": "10.6.1",
   "title": "Re-arranging Sentences of a Paragraph",
   "page": 295
  },
  {
   "number": "10.6.2",
   "title": "Punctuations",
   "page": 295
  },
  {
   "number": "10.6.3",
   "title": "Confusing words",
   "page": 299
  },
  {
   "number": "10.6.4",
   "title": "Writing an Expository Texts",
   "page": 301
  }
 ],
 "G12-ENGL-U1-S1": [
  {
   "number": "1A.1",
   "title": "Listening Text A: Development Projects in Addis Ababa",
   "page": 1
  },
  {
   "number": "1A.2",
   "title": "Listening text B: Innovation for Business and Development",
   "page": 3
  }
 ],
 "G12-ENGL-U1-S2": [
  {
   "number": "1B.1",
   "title": "Pronunciation",
   "page": 5
  },
  {
   "number": "1B.2",
   "title": "Pair Discussion",
   "page": 6
  },
  {
   "number": "1B.3",
   "title": "Public Speaking",
   "page": 7
  }
 ],
 "G12-ENGL-U1-S3": [
  {
   "number": "1C.1",
   "title": "Reading text A: Ethiopian Communities Mobilize to",
   "page": 8
  },
  {
   "number": "1C.2",
   "title": "Reading text B: Reading for Detail",
   "page": 10
  }
 ],
 "G12-ENGL-U1-S4": [
  {
   "number": "1D.1",
   "title": "Contextual Meaning",
   "page": 14
  },
  {
   "number": "1D.2",
   "title": "Text Completion Using the Correct Form of the Words",
   "page": 14
  },
  {
   "number": "1D.3",
   "title": "Verbal Reasoning Exercise",
   "page": 15
  }
 ],
 "G12-ENGL-U1-S5": [
  {
   "number": "1E.1",
   "title": "Cohesion: Using Comparing and Contrasting Devices",
   "page": 16
  },
  {
   "number": "1E.2",
   "title": "Fragments",
   "page": 19
  }
 ],
 "G12-ENGL-U1-S6": [
  {
   "number": "1F.1",
   "title": "Rearranging Words and Phrases to Make Meaningful",
   "page": 20
  },
  {
   "number": "1F.3",
   "title": "Paragraph Writing: Write a Comparing and Contrasting",
   "page": 21
  },
  {
   "number": "1F.4",
   "title": "Writing a Paragraph Based on Information in the Chart",
   "page": 22
  }
 ],
 "G12-ENGL-U2-S1": [
  {
   "number": "2A.1",
   "title": "Time Management Skills",
   "page": 24
  },
  {
   "number": "2A.2",
   "title": "Listening text B: Procrastination",
   "page": 26
  }
 ],
 "G12-ENGL-U2-S2": [
  {
   "number": "2B.1",
   "title": "Giving Reason",
   "page": 27
  }
 ],
 "G12-ENGL-U2-S3": [
  {
   "number": "2C.1",
   "title": "Reading text A: Time Management and Productivity",
   "page": 29
  },
  {
   "number": "2C.2",
   "title": "Reading text B: Cultural Views of Time Management",
   "page": 32
  }
 ],
 "G12-ENGL-U2-S5": [
  {
   "number": "2E.1",
   "title": "Expressing Result",
   "page": 40
  },
  {
   "number": "2E.2",
   "title": "Wishes",
   "page": 42
  },
  {
   "number": "2E.3",
   "title": "Gerund",
   "page": 45
  }
 ],
 "G12-ENGL-U2-S6": [
  {
   "number": "2F.1",
   "title": "Run-on Sentences",
   "page": 47
  },
  {
   "number": "2F.2",
   "title": "Jumbled Paragraphs",
   "page": 50
  }
 ],
 "G12-ENGL-U3-S3": [
  {
   "number": "3C.2",
   "title": "Reading Text B: Evidence of Road Traffic Accident in Africa",
   "page": 62
  }
 ],
 "G12-ENGL-U3-S4": [
  {
   "number": "3D.1",
   "title": "Contextual Meaning",
   "page": 65
  },
  {
   "number": "3D.2",
   "title": "Antonyms",
   "page": 65
  }
 ],
 "G12-ENGL-U3-S5": [
  {
   "number": "3E.1",
   "title": "Tense Balance in Conditional Sentences",
   "page": 66
  },
  {
   "number": "3E.2",
   "title": "Participles and Participles Phrases",
   "page": 68
  },
  {
   "number": "3E.3",
   "title": "Misplaced Participles/ Misplaced Modifiers",
   "page": 69
  }
 ],
 "G12-ENGL-U3-S6": [
  {
   "number": "3F.1",
   "title": "Jumbled Paragraphs of a Narrative Essay",
   "page": 70
  },
  {
   "number": "3F.2",
   "title": "Steps to Write a Narrative Essay",
   "page": 71
  }
 ],
 "G12-ENGL-U4-S1": [
  {
   "number": "4A.1",
   "title": "Ownership of Natural Resources",
   "page": 74
  },
  {
   "number": "4A.2",
   "title": "Listening text B: Community-Based Natural Resource",
   "page": 76
  }
 ],
 "G12-ENGL-U4-S2": [
  {
   "number": "4B.1",
   "title": "Ways of Agreeing and Disagreeing",
   "page": 77
  },
  {
   "number": "4B.2",
   "title": "Syllables and Stress",
   "page": 79
  }
 ],
 "G12-ENGL-U4-S3": [
  {
   "number": "4C.1",
   "title": "Reading text A: Integrated Natural Resource Management",
   "page": 84
  }
 ],
 "G12-ENGL-U4-S4": [
  {
   "number": "4D.1",
   "title": "Vocabulary from the Reading Passage",
   "page": 90
  },
  {
   "number": "4D.2",
   "title": "Analogy",
   "page": 90
  },
  {
   "number": "4D.3",
   "title": "Phrasal Verbs",
   "page": 91
  }
 ],
 "G12-ENGL-U4-S5": [
  {
   "number": "4E.1",
   "title": "Adverbial Clauses of Time",
   "page": 93
  }
 ],
 "G12-ENGL-U4-S6": [
  {
   "number": "4F.1",
   "title": "Dangling Modifier",
   "page": 96
  },
  {
   "number": "4F.2",
   "title": "Expository Essay Writing",
   "page": 99
  }
 ],
 "G12-ENGL-U5-S1": [
  {
   "number": "5A.1",
   "title": "Listening text A: Mechanized Agriculture",
   "page": 103
  },
  {
   "number": "5A.2",
   "title": "Listening text B: Mechanized Agricultural Tools",
   "page": 105
  }
 ],
 "G12-ENGL-U5-S2": [
  {
   "number": "5B.1",
   "title": "Asking for information ( ‘yes or no’ questions and ‘Wh’ questions)",
   "page": 107
  },
  {
   "number": "5B.2",
   "title": "Interview",
   "page": 108
  },
  {
   "number": "5B.3",
   "title": "Public Speaking",
   "page": 108
  }
 ],
 "G12-ENGL-U5-S3": [
  {
   "number": "5C.1",
   "title": "Benefits of Mechanized Agriculture",
   "page": 109
  },
  {
   "number": "5C.2",
   "title": "Reading text B: Modern Poultry Farm",
   "page": 112
  }
 ],
 "G12-ENGL-U5-S4": [
  {
   "number": "5D.1",
   "title": "Contextual Meaning",
   "page": 115
  },
  {
   "number": "5D.2",
   "title": "Analogy Exercises",
   "page": 116
  }
 ],
 "G12-ENGL-U5-S5": [
  {
   "number": "5E.1",
   "title": "Revision of Verbal: Gerund, Infinitives and Participles",
   "page": 117
  },
  {
   "number": "5E.2",
   "title": "Common Variation in Conditional Sentences",
   "page": 121
  }
 ],
 "G12-ENGL-U5-S6": [
  {
   "number": "5F.1",
   "title": "Editing Wordiness",
   "page": 123
  },
  {
   "number": "5F.2",
   "title": "Descriptive Essay",
   "page": 125
  }
 ],
 "G12-ENGL-U6-S1": [
  {
   "number": "6A.1",
   "title": "Listening text A: Green Economy Strategy to Withstand",
   "page": 129
  },
  {
   "number": "6A.2",
   "title": "Listening text B: Advice on Inclusive Green Economy",
   "page": 131
  }
 ],
 "G12-ENGL-U6-S2": [
  {
   "number": "6B.1",
   "title": "Asking for and Giving Advice",
   "page": 133
  },
  {
   "number": "6B.2",
   "title": "Expressing Purpose",
   "page": 136
  }
 ],
 "G12-ENGL-U6-S3": [
  {
   "number": "6C.1",
   "title": "Reading text A: Towards a Green Growth",
   "page": 139
  },
  {
   "number": "6C.2",
   "title": "Reading text B: Green Economy in Ethiopia",
   "page": 143
  }
 ],
 "G12-ENGL-U6-S4": [
  {
   "number": "6D.1",
   "title": "Words from the Reading Text",
   "page": 146
  },
  {
   "number": "6D.2",
   "title": "Analogy Based on Functions",
   "page": 147
  },
  {
   "number": "6D.3",
   "title": "Phrasal Verbs",
   "page": 148
  }
 ],
 "G12-ENGL-U6-S5": [
  {
   "number": "6E.1",
   "title": "Relative Pronouns",
   "page": 149
  }
 ],
 "G12-ENGL-U6-S6": [
  {
   "number": "6F.1",
   "title": "Faulty Parallelism",
   "page": 151
  },
  {
   "number": "6F.2",
   "title": "Comparing two pie-charts",
   "page": 154
  },
  {
   "number": "6F.3",
   "title": "Essay Writing",
   "page": 157
  }
 ],
 "G12-ENGL-U7-S1": [
  {
   "number": "7A.1",
   "title": "Listening text A: Celebrating National Prides",
   "page": 158
  }
 ],
 "G12-ENGL-U7-S3": [
  {
   "number": "7C.1",
   "title": "Reading Text A: Mega Projects of Countries",
   "page": 164
  },
  {
   "number": "7C.2",
   "title": "Reading Text B: A poem",
   "page": 168
  }
 ],
 "G12-ENGL-U7-S4": [
  {
   "number": "7D.1",
   "title": "Contextual Meaning",
   "page": 170
  },
  {
   "number": "7D.2",
   "title": "Analogy Exercise",
   "page": 171
  },
  {
   "number": "7D.3",
   "title": "Phrasal Verbs",
   "page": 172
  }
 ],
 "G12-ENGL-U7-S5": [
  {
   "number": "7E.1",
   "title": "Direct and Indirect Speeches",
   "page": 172
  },
  {
   "number": "7E.3",
   "title": "Vague Pronoun Reference",
   "page": 176
  }
 ],
 "G12-ENGL-U7-S6": [
  {
   "number": "7F.1",
   "title": "Punctuations",
   "page": 177
  },
  {
   "number": "7F.2",
   "title": "Rearrange Jumbled Paragraphs of Narrative Essay",
   "page": 178
  },
  {
   "number": "7F.3",
   "title": "Narrative Essay Writing",
   "page": 179
  }
 ],
 "G12-ENGL-U8-S1": [
  {
   "number": "8A.1",
   "title": "Listening text A: Fundamentals of Telemedicine",
   "page": 181
  },
  {
   "number": "8A.2",
   "title": "Listening text B: Benefits of Telemedicine",
   "page": 182
  }
 ],
 "G12-ENGL-U8-S2": [
  {
   "number": "8B.1",
   "title": "Meeting",
   "page": 183
  },
  {
   "number": "8B.2",
   "title": "Oral Presentation",
   "page": 189
  }
 ],
 "G12-ENGL-U8-S3": [
  {
   "number": "8C.1",
   "title": "Reading text A: Integrated Telemedicine",
   "page": 189
  }
 ],
 "G12-ENGL-U8-S4": [
  {
   "number": "8D.1",
   "title": "Words from the Reading Passage",
   "page": 198
  },
  {
   "number": "8D.2",
   "title": "Cloze Test",
   "page": 199
  },
  {
   "number": "8D.3",
   "title": "Analogy Exercise",
   "page": 200
  },
  {
   "number": "8D.4",
   "title": "Commonly Confusing Words",
   "page": 201
  },
  {
   "number": "8D.5",
   "title": "Phrasal Verbs",
   "page": 202
  }
 ],
 "G12-ENGL-U8-S5": [
  {
   "number": "8E.1",
   "title": "Active and Passive voice",
   "page": 204
  },
  {
   "number": "8E.2",
   "title": "Verbs and Prepositions",
   "page": 206
  },
  {
   "number": "8E.3",
   "title": "Pronoun and Adverb Changes in Reported Speech",
   "page": 210
  }
 ],
 "G12-ENGL-U8-S6": [
  {
   "number": "8F.1",
   "title": "Argumentative Essay",
   "page": 212
  }
 ],
 "G12-ENGL-U9-S1": [
  {
   "number": "9A.2",
   "title": "Listening text B: Orientations to Conflict Situations",
   "page": 217
  }
 ],
 "G12-ENGL-U9-S2": [
  {
   "number": "9B.1",
   "title": "Describing People",
   "page": 219
  },
  {
   "number": "9B.2",
   "title": "Drama",
   "page": 221
  }
 ],
 "G12-ENGL-U9-S3": [
  {
   "number": "9C.1",
   "title": "Reading text A: Conflict Managing Models for Managing",
   "page": 222
  }
 ],
 "G12-ENGL-U9-S4": [
  {
   "number": "9D.1",
   "title": "Word Relationship",
   "page": 226
  },
  {
   "number": "9D.2",
   "title": "Analogy Exercise",
   "page": 227
  }
 ],
 "G12-ENGL-U9-S5": [
  {
   "number": "9E.1",
   "title": "Pattern of the Verb with ‘Wish’",
   "page": 228
  },
  {
   "number": "9E.2",
   "title": "Faulty Subject Verb Agreements",
   "page": 229
  },
  {
   "number": "9E.3",
   "title": "Reported Speech - Tense Change Revision",
   "page": 231
  }
 ],
 "G12-ENGL-U9-S6": [
  {
   "number": "9F.1",
   "title": "Punctuation",
   "page": 234
  },
  {
   "number": "9F.3",
   "title": "An application Letter",
   "page": 238
  }
 ],
 "G12-ENGL-U10-S1": [
  {
   "number": "10A.1",
   "title": "Listening text A: What is Robotics?",
   "page": 243
  },
  {
   "number": "10A.2",
   "title": "Listening text B: Robotics in Ethiopia",
   "page": 245
  }
 ],
 "G12-ENGL-U10-S2": [
  {
   "number": "10B.1",
   "title": "Interviewing",
   "page": 246
  }
 ],
 "G12-ENGL-U10-S3": [
  {
   "number": "10C.1",
   "title": "Reading text A: Robotic Manipulation",
   "page": 247
  },
  {
   "number": "10C.2",
   "title": "Reading text B: Assistive Robots",
   "page": 249
  }
 ],
 "G12-ENGL-U10-S4": [
  {
   "number": "10D.1",
   "title": "Words Related to Robotics",
   "page": 252
  },
  {
   "number": "10D.2",
   "title": "Analogy",
   "page": 253
  },
  {
   "number": "10D.3",
   "title": "Phrasal Verbs",
   "page": 254
  }
 ],
 "G12-ENGL-U10-S5": [
  {
   "number": "10E.1",
   "title": "Common Mistakes in Sentence Writing",
   "page": 255
  }
 ],
 "G12-ENGL-U10-S6": [
  {
   "number": "10F.2",
   "title": "Curriculum Vitae",
   "page": 261
  }
 ]
}

export const ENGLISH_DETAILS_META = {
 "generatedAt": "2026-09-24",
 "source": "data/knowledge/knowledge_base.sqlite",
 "grades": {
  "9": {
   "bookId": 17,
   "pagesWithText": 1,
   "totalPages": 237,
   "sections": 59,
   "sectionsWithDetails": 0
  },
  "10": {
   "bookId": 18,
   "pagesWithText": 324,
   "totalPages": 326,
   "sections": 58,
   "sectionsWithDetails": 41
  },
  "11": {
   "bookId": 19,
   "pagesWithText": 5,
   "totalPages": 290,
   "sections": 62,
   "sectionsWithDetails": 0
  },
  "12": {
   "bookId": 20,
   "pagesWithText": 269,
   "totalPages": 270,
   "sections": 60,
   "sectionsWithDetails": 56
  }
 }
}
